disabled_rules: # rule identifiers to exclude from running
  - line_length
  - force_cast
  - trailing_whitespace
  - todo
  - identifier_name
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - fastlane
file_length:
  warning: 1200
  error: 1600
type_body_length:
  warning: 600
  error: 800
function_body_length:
  warning: 80
  error: 120
large_tuple:
  warning: 5
  error: 6
cyclomatic_complexity:
  warning: 20
  error: 30

